config/routes.rb
BreweryLocator::Application.routes.draw do
  devise_for :users

  root 'map#index'

  get 'map/getBreweryCoords' => 'map#getBreweryMarkerCoords'
  get 'admin/deleteBreweries' => 'breweries#deleteBreweries'

  get 'admin' => 'admin#index'
  get 'import_breweries_api' => 'breweries#importBreweriesFromAPI'
  post 'admin/setBreweryActive' => 'breweries#setBreweryActive'
  get 'admin/getCurrentUserState' => 'breweries#getCurrentUserState'

  

    scope 'admin' do
      resources :breweries
    end
end

app/models/brewery.rb
require 'open-uri'

class Brewery < ActiveRecord::Base
	geocoded_by :address_city_state # address is an attribute of Brewery model
	# reverse_geocoded_by :latitude, :longitude
	# the callback to set longitude and latitude
  	after_validation :geocode
  	# :if => lambda{ |obj| obj.address_changed? }
  	# if: ->(brewery){ brewery.address.present? and brewery.address_changed? }

  	# geocode by all 3
  	def address_city_state
  		self.address + ' ' + self.city + ', ' + self.state
	end

  	# TODO import WA breweries that are close to OR border ( maybe 50miles from border?).   Should include Wa in the Gorge and in the couv.
	def self.importBreweriesFromAPI()
		# GET OREGON BREWERIES
		doc = Nokogiri::XML(open("http://beermapping.com/webservice/locstate/05a1a701dca974e16978f0c9027709b1/or"))
		root = doc.root
		items = root.xpath("//location")
		counter = 0
		items.each do |i|
			if i.at_xpath("status").text == 'Brewpub' or i.at_xpath("status").text == 'Brewery' or i.at_xpath("status").text == 'Beer Bar'
				counter += 1
				coords = Nokogiri::XML(open("http://beermapping.com/webservice/locmap/05a1a701dca974e16978f0c9027709b1/#{i.at_xpath("id").text}"))
				# update brewery
				if Brewery.exists?(:location_id => i.at_xpath("id").text)
					b = Brewery.find_by(location_id: i.at_xpath("id").text)
					b.name = i.at_xpath("name").text
					# b.lat = coords.xpath("//lat").text
					# b.long = coords.xpath("//lng").text
					b.city = i.at_xpath("city").text
					b.address = i.at_xpath("street").text
					b.state = i.at_xpath("state").text
					b.save
				# create brewery
				else
					# took out lat and long... geolocation doign for us
					Brewery.create({location_id: i.at_xpath("id").text,name: i.at_xpath("name").text,city: i.at_xpath("city").text,address: i.at_xpath("street").text,state: i.at_xpath("state").text})
				end
			end
		end

		# GET WA BREWERIES
		wadoc = Nokogiri::XML(open("http://beermapping.com/webservice/loccity/05a1a701dca974e16978f0c9027709b1/vancouver,wa"))
		waroot = wadoc.root
		waitems = waroot.xpath("//location")
		waitems.each do |j|
			if j.at_xpath("status").text == 'Brewpub' or j.at_xpath("status").text == 'Brewery' or j.at_xpath("status").text == 'Beer Bar'
				counter += 1
				wacoords = Nokogiri::XML(open("http://beermapping.com/webservice/locmap/05a1a701dca974e16978f0c9027709b1/#{j.at_xpath("id").text}"))
				# update brewery
				if Brewery.exists?(:location_id => j.at_xpath("id").text)
					wb = Brewery.find_by(location_id: j.at_xpath("id").text)
					wb.name = j.at_xpath("name").text
					# wb.lat = wacoords.xpath("//lat").text
					# wb.long = wacoords.xpath("//lng").text
					wb.city = j.at_xpath("city").text
					wb.address = j.at_xpath("street").text
					wb.state = j.at_xpath("state").text
					wb.save
				# create brewery
				else
					# took out lat and long... geolocation doign for us
					Brewery.create({location_id: j.at_xpath("id").text,name: j.at_xpath("name").text,city: j.at_xpath("city").text,address: j.at_xpath("street").text,state: j.at_xpath("state").text})
				end
			end
		end

		return counter.to_s
	end

	# parse the state from the users current lat and long
	def self.getCurrentUserState(lat,long)
		location = Geocoder.address([lat,long])
		cityState = location.match('((?:\w|\s)+),\s(AL|AK|AS|AZ|AR|CA|CO|CT|DE|DC|FM|FL|GA|GU|HI|ID|IL|IN|IA|KS|KY|LA|ME|MH|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|MP|OH|OK|OR|PW|PA|PR|RI|SC|SD|TN|TX|UT|VT|VI|VA|WA|WV|WI|WY)')
		return cityState.to_s.split(',')[1].strip
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout "admin"
	before_action :authenticate_user!, :only => :index
	
	def index()
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => :getCurrentUserState
  layout "admin"

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.order(name: :asc).paginate(:page => params[:page],:per_page => 30)
    # TODO change this to the current location from JS APi
    # r = Brewery.near([request.location.latitude,request.location.longitude], 1,:order => :distance)
    # @withinTen = r.all
    @withinTen = {}
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    puts "this is create"
    puts brewery_params
    @brewery = Brewery.new(brewery_params)
    puts "in save"
    puts @brewery.to_yaml
    respond_to do |format|
      if @brewery.save
        puts "saved"
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render action: 'show', status: :created, location: @brewery }
      else
        puts "didnt save"
        format.html { render action: 'new' }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url }
      format.json { head :no_content }
    end
  end

  def importBreweriesFromAPI()
    @importTotal = Brewery.importBreweriesFromAPI()
    redirect_to breweries_url,notice: 'Breweries Imported.'
  end

  def deleteBreweries()
    Brewery.delete_all()
    redirect_to breweries_url,notice: 'Breweries Deleted.'
  end

  # check the state the user lat/long in 
  def getCurrentUserState()
    usersState = Brewery.getCurrentUserState(params[:lat],params[:long])
    # reverse geolocate lat long and get users state
    render json:{state: usersState}, status: 200
  end

  # set brewery to active / inactive 
  # IDEA!.. could this just use the edit or update method above?...
  def setBreweryActive()
    # brewer_id and answer coming in from the ajax call
    b = Brewery.find(params[:brewery_id])
    b.is_active = params[:answer]
    b.save
    render :nothing => true, :status => 200
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :address,:city,:state,:notes, :lat, :long) if params[:brewery] else params.permit(:name, :address,:city,:state,:notes, :latitude, :longitude)
      # params.permit(:name, :address,:city,:state,:notes, :latitude, :longitude)
    end
end

app/controllers/map_controller.rb
class MapController < ApplicationController

	def index()
		# puts location.methods
	end

	def getBreweryMarkerCoords()
		breweries = Brewery.order(name: :asc).where(is_active:true).all
		render :json => breweries.as_json
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/views/admin/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12" style="padding-top:50px;">
			<h1>A better Bootstrap starter template.</h1>
			<p>Complete with pre-defined file paths that you won't have to change!</p>
		</div>
	</div>
</div><!-- /.container -->

app/views/breweries/_form.html.erb
   <%= form_for(@brewery,:html => { :class => "form-horizontal" }) do |f| %>
    <% if @brewery.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>
        <ul>
        <% @brewery.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :name %><br /><br />
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :address %><br><br />
      <%= f.text_field :address, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :city %><br><br />
      <%= f.text_field :city, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :state %><br><br />
      <%= f.text_field :state, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :latitude %><br><br />
      <%= f.text_field :latitude, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :longitude %><br><br />
      <%= f.text_field :longitude, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :notes %><br><br />
      <%= f.text_area :notes, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :is_active,'Active' %><br /><br />
      <%= f.radio_button :is_active, true %><br />
      <%= f.label :is_active,'Inactive' %><br /><br />
      <%= f.radio_button :is_active, false %>
    </div>

    <div class="form-group">
      <%= f.submit class: "btn btn-default" %>
    </div>
  <% end %>

app/views/breweries/edit.html.erb
<div style="padding-left:25px;padding-bottom:50px;">
	<h1>Editing <%= @brewery.name %></h1>
	<%= render 'form' %>

	<%= link_to 'Show', @brewery, :class => 'btn btn-success pull-left' %>
	<%= link_to 'Back', breweries_path, :class => 'btn btn-success pull-left' %>
</div>

app/views/breweries/index.html.erb
<div class="container">
  <% if flash[:notice] -%>
    <p class='notice'><h2><%=h flash[:notice] %></h2></p>
  <% end -%>
    <div class="row">
        <div class="col-lg-12" >
            <div class="page-header">
                <h1>Breweries (<%= @breweries.count %>)</h1>
                <div class="row" style="a { color: #fff !important }">
                  <span style="pull-right">
                    <%= link_to 'Pending', new_brewery_path, :class => 'btn btn-success pull-right' %>&nbsp;&nbsp;&nbsp;
                  </span>
                  <span style="pull-right">
                    <%= link_to 'New Brewery', new_brewery_path, :class => 'btn btn-success pull-right' %>&nbsp;&nbsp;&nbsp;
                  </span>
                  <span style="pull-right">
                    <%= link_to 'API Import', import_breweries_api_path, :class => 'btn btn-success pull-right' %>
                  </span>
                  <span style="pull-right">
                    <%= link_to 'Clear Breweries', '/admin/deleteBreweries', :class => 'btn btn-success pull-right',data: { confirm: 'Are you sure?'} %>
                  </span>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
      <span style="padding-left:25px;">
        <b> Breweries within 1 mile </b> &nbsp; <%=  @withinTen.count %>&nbsp;
        <% @withinTen.each do |r| %>
          <%= r.name %>,
        <% end %>
      </span>
    </div><br />
    <div class="row">
        <div class="col-lg-12">
            <table class="table" id="table">
                <thead>
                    <tr>
                        <th>Visible</th>
                        <th>Name</th>
                        <th>Address</th>
                        <th>Lat</th>
                        <th>Long</th>
                    </tr>
                </thead>
                <tbody>
                  <% @breweries.each do |brewery| %>
                    <tr>
                      <td style="width:100px;">
                        <div class="btn-group btn-toggle"> 
                          <button  
                            <% if brewery.is_active? %>
                              class="btn btn-sm btn-primary active"
                            <%else%>
                              class="btn btn-sm btn-default"
                            <%end%>
                            id="<%= brewery.id %>_true">ON
                          </button>
                          <button
                            <% if brewery.is_active? %>
                            class="btn btn-sm btn-default"
                            <%else%>
                              class="btn btn-sm btn-primary active"
                            <%end%>
                            id="<%= brewery.id %>_false">OFF
                          </button>
                        </div>
                      </td>
                      <td><%= brewery.name %></td>
                      <td><%= brewery.address %> <%= brewery.city %>, <%= brewery.state %></td>
                      <td><%= brewery.latitude %></td>
                      <td><%= brewery.longitude %></td>
                      <td><%= link_to 'Show', brewery %></td>
                      <td><%= link_to 'Edit', edit_brewery_path(brewery) %></td>
                      <td><%= link_to 'Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                  <%= will_paginate @breweries %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @brewery.name %>
</p>
<p>
  <strong>Address:</strong>
  <%= @brewery.address %>
</p>
<p>
  <strong>City:</strong>
  <%= @brewery.city %>
</p>
<p>
  <strong>State:</strong>
  <%= @brewery.state %>
</p>
<p>
  <strong>Notes:</strong>
  <%= @brewery.notes %>
</p>
<p>
  <strong>Lat:</strong>
  <%= @brewery.latitude %>
</p>
<p>
  <strong>Long:</strong>
  <%= @brewery.longitude %>
</p>
<%= link_to 'Edit', edit_brewery_path(@brewery),:class => 'btn btn-success pull-left' %>
<%= link_to 'Back', breweries_path,:class => 'btn btn-success pull-left' %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BreweryLocator</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "breweries" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/admin">Oregon Brewery Locator</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav">
				<li><a href="/admin/breweries">Breweries</a></li>
				<li><a href="">Users</a></li>
				<li><a href="">Events</a></li>
			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container -->
</nav>
<!-- <div style="padding-bottom:50px;"></div> -->

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="app" lang="en">
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1,width=device-width">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="description" content="">
    <meta name="author" content="">
  	<title>Oregon Brewery Locator</title>
 	  <%= stylesheet_link_tag    "application", media: "all" %>
  	<script src="http://maps.google.com/maps/api/js?v=3.2&sensor=false"></script>
  	<%= javascript_include_tag "application", controller_name %>
  	<%= csrf_meta_tags %>

  	<link rel="apple-touch-icon" href="assets/img/favicon-152.png">
    <link rel="shortcut icon" sizes="196x196" href="assets/img/favicon-196.png">

  	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.js"></script>
        <script src="assets/js/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<%= yield %>

</body>
</html>

app/views/map/index.html.erb
<div ng-controller="IndexCtrl">
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<!-- {{centerPoint.lat }} -->
	  	<!-- {{centerPoint.lng }} -->
	      <div class="navbar-header">
	        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	        </button>
	        <a class="navbar-brand" href="#">OR Brewery Locator</a>
	      </div>
	      <div class="navbar-collapse collapse">
	        <form class="navbar-form navbar-right" role="search">
	          <div class="form-group has-feedback navbar-right">
	              <input id="searchbox" type="text" placeholder="Search" class="form-control">
	              <span id="searchicon" class="fa fa-search form-control-feedback"></span>
	          </div>
	        </form>
	        <ul class="nav navbar-nav">
	           <li><a href="#" data-toggle="collapse" data-target=".navbar-collapse.in" ng-click="sidebarToggle()"><i class="fa fa-list" style="color: white"></i>&nbsp;&nbsp;Sidebar</a></li>
	          <li><a href="#" data-toggle="collapse" data-target=".navbar-collapse.in" onclick="$('#aboutModal').modal('show'); return false;"><i class="fa fa-question-circle" style="color: white"></i>&nbsp;&nbsp;About</a></li>
	          <li class="dropdown"></li>
	        </ul>
	      </div><!--/.navbar-collapse -->
	    </div>

	    <!-- MAP -->
	    <leaflet center="centerPoint" layers="layers" markers="markers" defaults="defaults" id="map"></leaflet>
	    
	    <!-- SIDEBAR  -->
	    <div id="sidebar">
	      <h2>Breweries </h2>
	      	<ul ng-repeat="b in results | orderBy:'name'">
	      	<li ng-click="showBrewery(b)">{{b.message}}</li>
	      	</ul>
	      </p>
	    </div>
	    <!-- // END SIDEBAR -->

	    <!--- TODO.. add loader back in mabe a spinner icon?.. something liek that -->
	    <div id="loading">
	      <div class="loading-indicator">
	        <div class="progress progress-striped active">
	          <div class="progress-bar progress-bar-info" style="width: 100%"></div>
	        </div>
	      </div>
	    </div>

	    <div class="modal fade" id="aboutModal" tabindex="-1" role="dialog">
	      <div class="modal-dialog modal-lg">
	        <div class="modal-content">
	          <div class="modal-header">
	            <button class="close" type="button" data-dismiss="modal" aria-hidden="true">&times;</button>
	            <h4 class="modal-title">About This App</h4>
	          </div>
	          <div class="modal-body">
	            <ul class="nav nav-tabs" id="aboutTabs">
	              <li class="active"><a href="#about" data-toggle="tab"><i class="fa fa-question-circle"></i>&nbsp;About the project</a></li>
	              <li><a href="#contact" data-toggle="tab"><i class="fa fa-envelope"></i>&nbsp;Add Brewery</a></li>
	            </ul>
	            <div class="tab-content" id="aboutTabsContent" style="padding-top: 10px;">
	              <div class="tab-pane fade active in" id="about">
	                <p>
	                	I made this... is fucking badass and it finds breweries...<br /><br />
	                	Organic sustainable lomo, +1 irony McSweeney's skateboard Portland PBR tattooed farm-to-table Terry Richardson Williamsburg. Organic farm-to-table wolf, next level shit put a bird on it freegan American Apparel Williamsburg chambray gentrify viral you probably haven't heard of them keffiyeh Cosby sweater. Pitchfork photo booth fuck, 
	                </p>
	              </div>
	              <div class="tab-pane fade" id="contact">
	                <form id="contact-form" ng-submit="processForm()">
	                  <div class="well well-sm">
	                  	<div id="messages" ng-show="message">{{ message }}</div>
	                  	<div class="form-group">
	                    	<label for="first-name">Brewery Name:</label><br /><br />
	                        <input type="text" class="form-control" id="first-name" ng-model="brewery.name">
	                    </div>
	                    <!-- 
	                    <div class="form-group">
	                        <label for="email">Email:</label><br /><br />
	                        <input type="text" class="form-control" id="email" ng-model="brewery.email">
	                    </div> 
	                    -->
	                    <div class="form-group">
	                        <label for="city">City:</label><br /><br />
	                        <input type="text" class="form-control" id="city" ng-model="brewery.city">
	                    </div>
	                    <div class="form-group">
	                        <label for="address">Address:</label><br /><br />
	                        <input type="text" class="form-control" id="address" ng-model="brewery.address">
	                    </div>
	                    <div class="form-group">
	                        <label for="state">State:</label><br /><br />
	                        <input type="text" class="form-control" id="state" ng-model="brewery.state">
	                    </div>
	                    <!-- 
	                    <div class="form-group">
	                        <label for="message">Message:</label><br /><br />
	                        <textarea class="form-control" rows="8" id="message" ng-model="brewery.message"></textarea>
	                    </div> 
	                    -->
	                    <div class="col-md-12">
	                    	<p>
	                    	  <input type="submit" id="submit" value="Submit" />
	                          <!-- <button type="submit" class="btn btn-primary pull-right" data-dismiss="modal">Submit</button> -->
	                        </p>
	                    </div>
	                </form>
	              </div> 
	            </div>
	          </div>
	        </div><!-- /.modal-content -->
	      </div><!-- /.modal-dialog -->
	    </div><!-- /.modal -->

	    <div class="modal fade" id="legendModal" tabindex="-1" role="dialog">
	      <div class="modal-dialog">
	        <div class="modal-content">
	          <div class="modal-header">
	            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	            <h4 class="modal-title">Map Legend</h4>
	          </div>
	          <div class="modal-body">
	            <p>Map Legend goes here...</p>
	          </div>
	        </div><!-- /.modal-content -->
	      </div><!-- /.modal-dialog -->
	    </div><!-- /.modal -->

	  	<div class="modal fade" id="featureModal" tabindex="-1" role="dialog">
	      <div class="modal-dialog">
	        <div class="modal-content">
	          <div class="modal-header">
	            <button class="close" type="button" data-dismiss="modal" aria-hidden="true">&times;</button>
	            <h4 class="modal-title text-primary" id="feature-title"></h4>
	          </div>
	          <div class="modal-body" id="feature-info"></div>
	        </div><!-- /.modal-content -->
	      </div><!-- /.modal-dialog -->
	    </div><!-- /.modal -->
	    
  </div>